services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend_model
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "9800:9000"

    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
#            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
