services:
    laravel.test:
        container_name: laravel_app
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
#            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
#            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            XDEBUG_MODE: develop,debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes
            XDEBUG_IDEKEY: PHPSTORM
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
#            - './docker/20-xdebug.ini:/etc/php/8.4/cli/conf.d/20-xdebug.ini'
        networks:
            - sail
        depends_on: {  }
networks:
    sail:
        driver: bridge
